# Generated by Django 3.0.5 on 2020-04-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
    ]
