# Generated by Django 3.0.5 on 2020-10-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
