# Generated by Django 2.1.4 on 2019-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='notice',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now=True),
        ),
    ]
