# Generated by Django 2.1.4 on 2020-02-17 04:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200119_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=blog.models.upload_location, width_field='width'),
        ),
    ]
