# Generated by Django 2.1.4 on 2020-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200216_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='height',
            new_name='height_field',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='width',
            new_name='width_field',
        ),
    ]
