# Generated by Django 2.1.4 on 2020-02-17 04:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200216_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='height',
            new_name='height_field',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='width',
            new_name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
    ]
