# Generated by Django 3.0.5 on 2020-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='json_files',
            field=models.TextField(default=None, null=True),
        ),
    ]
