# Generated by Django 3.0.5 on 2020-04-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200421_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context',
        ),
    ]
