# Generated by Django 3.0.5 on 2020-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201024_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json_details_en',
            field=models.TextField(default=None, null=True),
        ),
    ]
