# Generated by Django 3.0.5 on 2020-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200408_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typeId',
        ),
    ]
