# Generated by Django 3.0.5 on 2020-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200408_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='json_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
