# Generated by Django 3.0.5 on 2020-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200412_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.TextField(default=None, null=True),
        ),
    ]
