# Generated by Django 3.0.5 on 2020-04-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200413_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='json_description',
            new_name='json_details',
        ),
    ]
