# Generated by Django 3.0.5 on 2020-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producttype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defaultImage',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='json_images',
            field=models.TextField(default=None, null=True),
        ),
        # migrations.RunSQL('UPDATE products SET json_images= (SELECT ) ')
    ]
