# Generated by Django 3.0.5 on 2020-10-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200428_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='json_details',
            new_name='json_details_esp',
        ),
    ]
