# Generated by Django 3.0.5 on 2020-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201024_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='json_details_eng',
            field=models.TextField(default=None, null=True),
        ),
    ]
