# Generated by Django 3.0.5 on 2020-10-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_json_details_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='json_details_esp',
            new_name='json_details_es',
        ),
    ]
