# Generated by Django 3.0.5 on 2020-10-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201024_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='json_details_eng',
            new_name='json_details_en',
        ),
    ]
