# Generated by Django 3.0.5 on 2020-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201024_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
